// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-JN6J-8CDVZUgU8URLkyWnWk208-vX2E',
    appId: '1:20849895416:android:491b70bf811b0f3b9a580d',
    messagingSenderId: '20849895416',
    projectId: 'zsquadfitness',
    databaseURL:
        'https://zsquadfitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsquadfitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfuNnCqJDvadVBFBoJ0Ofy__BXVHqe_QM',
    appId: '1:20849895416:ios:203b6e63682eb3d19a580d',
    messagingSenderId: '20849895416',
    projectId: 'zsquadfitness',
    databaseURL:
        'https://zsquadfitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsquadfitness.firebasestorage.app',
    androidClientId:
        '20849895416-difo5n3sg6tbd4rkkc32c8nqkk3q0i2c.apps.googleusercontent.com',
    iosClientId:
        '20849895416-691eivuhcljmicu3dave6kkmepu5lbp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.zsquadfitness',
  );
}
